#io.k8s.api.apps.v1.Deployment(v1@deployment.json)
# K8 works with API versions to declare resources
# We have to declare the apiVersion and the kind of service/component
# services: deployment, service, pods, replicasets, crobjob, autoscalinggroup, horizontal pod scaling group (HPA)


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment



spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service


  replicas: 2

  # template to use its label for k8 service or any other 
  template: 
    metadata:
      labels:
        app: nginx # this label connects to the service or any other k8 components
    
    # defines the container spec
    spec:
      containers:
      - name: nginx
        image: rajsjohal/eng99_my_nginx:latest
        ports:
        - containerPort: 80

# Create a kubernetes nginx-service.yml